#!/bin/bash

# Helper for searching code base without searching through external code

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
    cd $DIR
    exec ack "$@" \
        --ignore-directory .tox \
        --ignore-directory dist \
        --ignore-directory build \
        --ignore-directory noseOfYeti.egg-info \
        --ignore-directory tools \
        --ignore-directory docs/.sphinx-build \
        --ignore-directory docs/_build \
)
