#!/usr/bin/env python3

from venvstarter import manager

(
    __import__("venvstarter")
    .manager("noy_pylama")
    .add_pypi_deps("pylama==7.7.1")
    .add_local_dep(
        "{here}",
        "..",
        version_file=(
            "noseOfYeti",
            "__init__.py",
        ),
        name="noseOfYeti=={version}",
    )
    .min_python("3.7")
    .run()
)
