#!/usr/bin/env python3

from venvstarter import manager

(
    __import__("venvstarter")
    .manager("sphinx-build")
    .add_requirements_file("{here}", "requirements.txt")
    .add_local_dep(
        "{here}",
        "..",
        version_file=(
            "noseOfYeti",
            "__init__.py",
        ),
        name="noseOfYeti=={version}",
    )
    .min_python("3.7")
    .run()
)
